/**
 * Generated by scripts/import_art.mjs from the battlefields drawn in ascii/minochar/battle/. Redraw them in minochar
 * and run `npm run import:art` instead of editing this file.
 *
 * Each battlefield is a list of looks the size of its arena. `art` is what is drawn; `solid` is the collision
 * mask ('#' = a body cannot be there): every drawn cell, plus the open ground no body could use or reach;
 * `markers` is where the opening puts everyone.
 */
import type {TerrainPieceLook} from "./terrain_art";

export const IMPORTED_DRAWINGS = {
    compound1a: [
        {
            art: [
                "                                                  ",
                "                                                  ",
                "          __/        |     ###################    ",
                "        _/           |    ####################    ",
                "                     |#######        ##   ///#    ",
                "                     |#######        ##      #    ",
                "                     |               ##      #    ",
                "                                     ##      #    ",
                "                                     ##      #    ",
                "                                     ##      ##   ",
                "                       ########      ##      ##   ",
                "                       ########      #       ##   ",
                "                              #      #       ##   ",
                "                              #              ##   ",
                "             /\\               #              ##   ",
                "  |            \\              #              ##   ",
                "  |                           ####           ##   ",
                " /`                              ##############   ",
                "/                                                 "
            ],
            solid: [
                "                                                  ",
                "                                                  ",
                "          ###        #     ###################    ",
                "        ##           #    ####################    ",
                "                     ########        ##   ####    ",
                "                     ########        ##      #    ",
                "                     #               ##      #    ",
                "                                     ##      #    ",
                "                                     ##      #    ",
                "                                     ##      ##   ",
                "                       ########      ##      ##   ",
                "                       ########      #       ##   ",
                "                              #      #       ##   ",
                "                              #              ##   ",
                "             ##               #              ##   ",
                "  #            #              #              ##   ",
                "  #                           ####           ##   ",
                "###                              ##############   ",
                "#                                                 "
            ],
            markers: [{ mark: '1', col: 41, row: 6 }, { mark: '3', col: 30, row: 7 }, { mark: '0', col: 8, row: 8 }, { mark: '2', col: 37, row: 14 }]
        }
    ],
    compound1b: [
        {
            art: [
                "                                                  ",
                "                                                  ",
                "    ##     ####            ######              /\\ ",
                "  ###         ##################################| ",
                "  #                   #[][][]               ##M#| ",
                "  ##                  #                     ##M#| ",
                "  ##                  #                     ## #  ",
                "  ##                 ##                     ## #  ",
                "  ##                 ##                        #  ",
                "  ##                 #################         #  ",
                "   #                 ######  ########          #  ",
                "   #                                           #  ",
                "   #                                           #  ",
                "   #                                          ##  ",
                "   #                                          ##  ",
                "   #                                          #   ",
                "   #88888888###########    #######           ##   ",
                "   #########################     ####        ##   ",
                "                                                  "
            ],
            solid: [
                "                                                  ",
                "                                                  ",
                "    ##     ####            ######              ###",
                "  ###         ####################################",
                "  #                   #######               ######",
                "  ##                  #                     ######",
                "  ##                  #                     ####  ",
                "  ##                 ##                     ####  ",
                "  ##                 ##                        #  ",
                "  ##                 #################         #  ",
                "   #                 ######  ########          #  ",
                "   #                                           #  ",
                "   #                                           #  ",
                "   #                                          ##  ",
                "   #                                          ##  ",
                "   #                                          #   ",
                "   ####################    #######           ##   ",
                "   #########################     ####        ##   ",
                "                                                  "
            ],
            markers: [{ mark: '1', col: 27, row: 6 }, { mark: '0', col: 12, row: 10 }, { mark: '2', col: 38, row: 13 }]
        }
    ]
} satisfies Record<string, TerrainPieceLook[]>;
